### ISSUE TITLE
Help with realsense gazebo plugin

### ISSUE THREAD

**Issue by Rudresh172** [yuan-0816/apex-aim-robot#1]
Hey Yuan,

I have been breaking my head to get the realsense plugin running on Gazebo Classic on my Ubuntu 22.04 ROS Humble. I came across your issue on the rtabmap_ros page. 

Would you be willing to help me with this?

**Comment by yuan-0816** [comment]
You can state your question [here](https://github.com/AirLab-Drone/drone_vslam)
Thx

**Comment by Rudresh172** [comment]
Thanks for the reply. I've added the issue there!
